### PR TITLE
Add events section on the landing page

### PR DESCRIPTION
**Pull request by steekam**
This PR closes issue #10

Build the responsive events sections on the homepage

## Notes
- The built design uses the sample events posters in the design from Figma.
- From the design every event card has it's own design. Perhaps there can be a standard event card design if the intention isn't to upload a designed poster for the events.

<details>
<summary>Screenshots</summary>

Large screen view
image

Mobile view
image

</details>

### CODE REVIEW

**Comment by johnGachihi** [comment]
Hey @steekam,
The horizontal padding for the banner and events sections are slightly inconsistent up to the `lg` breakpoint.

What do you think about lifting up the horizontal padding styling as below to make it easier to stay consistent (especially since there are two other sections coming up with the same horizontal padding)?
```jsx
<main>
  <Nav />
  <div className="px-5 md:px-8 lg:px-20">
    <Banner />
    <EventsPane />
    ...
  </div>
</main>
```

**Comment by steekam** [comment]
@johnGachihi, yes that's one possibility.
Is trying to avoid "extra" nesting divs a good goal? Haha.
I can make that modification though. It's a good suggestion.

**Comment by katungi** [comment]
Nice catch @johnGachihi and @steekam. I should we should come up with abstractions for spacing? I forgot to add that for colors as well. I had added a color in the tailwind config for standardization. Maybe we should do the same for spacing this sprint? What do you think?

**Comment by steekam** [comment]
How would the spacing abstractions look like in this case?

**Comment by katungi** [comment]
We can create a class that sets a certain padding so we can always call that class when we need to center a component as needed here. But we can do that later and refactor.

**Review by katungi — APPROVED** [review]
LGTM!
Awesome work @steekam

**Pull request merged**
