### PR TITLE
Animated value proposition header in landing page 

### PR DESCRIPTION
**Pull request by alexmagwe**
related to issue #15 

landingpage_animation

### CODE REVIEW

**Review by katungi — COMMENTED** [review]
Hey @alexmagwe. Just reviewing your code here, Could you please check on the merge conflicts? It will make my work easier. Plus I don't want to leave out anything from your code when resolving the conflicts. I will appreciate it!

**Comment by alexmagwe** [comment]
@katungi i dont understand what you mean by check on the merge conflicts

**Comment by alexmagwe** [comment]
@katungi i pulled from the develop branch and now im struggling to resolve the conflicts

**Comment by katungi** [comment]
Hey @alexmagwe, can we have a meeting to revolve this conflicts?

**Comment by alexmagwe** [comment]
yes that would be very helpful

**Pull request merged**
