### PR TITLE
Footer component

### PR DESCRIPTION
**Pull request by mevolkan**
Added the footer component

### CODE REVIEW

**Comment by katungi** [comment]
Hey @mevolkan , was this an existing issue? 
Asking because I can't find a discussion about this. Anyway, this was this weeks task board so thanks for being one step ahead.
I will review this last so we merge last sprint's PR's today. Awesome work!

**Comment by mevolkan** [comment]
hi @katungi 
It was not, just thought of it and implemented it.

Thank you for the feedback.

**Review by katungi — APPROVED** [review]
Hey @mevolkan , thanks for this PR, the footer is stunning.
But remember the flow next time, create an issue or claim an issue so that you get assigned to the project!

**Comment by mevolkan** [comment]
Thank you @katungi , I will

**Pull request merged**
