### PR TITLE
Finished the CallToAction

### PR DESCRIPTION
**Pull request by Mogakamo**
It is also responsive

### CODE REVIEW

**Comment by Mogakamo** [comment]
@katungi you can review my code.

**Comment by Mogakamo** [comment]
Fixes #8

**Comment by katungi** [comment]
Heeey @Mogakamo , I will review all PRs today. I was afk all weekend.

**Comment by Mogakamo** [comment]
No problem @Mogakamo

**Review by katungi — COMMENTED** [review]
Good work @Mogakamo

**Pull request merged**
